# Generated by Django 4.1.7 on 2023-03-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adocao'), ('A', 'Adotado')], default='P', max_length=1),
        ),
    ]
